#!/usr/bin/env python3

def add(e,y):
    x = a + b
    return x
def shift_right(e,d):
    y = e>>d
    return y

if __name__ == '__main__':
    name =input('Please enter your name: ')
    print(f'Hello {name}, and welcome to Python')
    a = int(input('Please enter a number: '))
    b = int(input('Please enter another number: '))
    answer1 = add(a,b)
    answer2 = shift_right(a,b)
    print(f'{a} >> {b} = {answer2}')
    print(f'{a} + {b} = {answer1}')
~                                     

#!/usr/bin/env python3
"""
Script outline for first script lab
Author: Joff Thyer, 2022
"""
# are we running as a script?
if __name__ == '__main__':
    name = input('Please enter your name: ')
    print(f'Hello {name}, and welcome to Python')
    a = int(input('Please enter a number: '))
    b = int(input('Please enter another number: '))
    print(f'{a} * {b} = {a*b}')
    print(f'{a} << {b} = {a<<b}')
~                                                                                 
~                                         
