#!/usr/bin/env python3

def add(e,y):
    x = a + b
    return x
def shift_right(e,d):
    y = e>>d
    return y

if __name__ == '__main__':
    name =input('Please enter your name: ')
    print(f'Hello {name}, and welcome to Python')
    a = int(input('Please enter a number: '))
    b = int(input('Please enter another number: '))
    answer1 = add(a,b)
    answer2 = shift_right(a,b)
    print(f'{a} >> {b} = {answer2}')
    print(f'{a} + {b} = {answer1}')
~                                     

#!/usr/bin/env python3
"""
Script outline for first script lab
Author: Joff Thyer, 2022
"""
# are we running as a script?
if __name__ == '__main__':
    name = input('Please enter your name: ')
    print(f'Hello {name}, and welcome to Python')
    a = int(input('Please enter a number: '))
    b = int(input('Please enter another number: '))
    print(f'{a} * {b} = {a*b}')
    print(f'{a} << {b} = {a<<b}')
~                                                                                 
~                                         
def xor(x, y):
    theanswer = x^y
    return theanswer

def modulus(x, y):
    theanswer= x % y
    return theanswer
if __name__ == '__main__':
    print(f'xor test: {xor(10, 20)}')
   #same for modulus
    print(f'modulus test: {modulus(10, 20)}')

#!/usr/bin/env python3
import mymath 
if __name__ == '__main__':

    print(f"You have imported the module named: {mymath.__name__}")
    name = input(f'Please enter your name: ')
    print(f'Hello {name}, and welcome to Python.')
    a = int(input(f'Please enter a number: '))
    b = int(input(f'Please enter another number: '))
    answer1 = mymath.xor(a,b)
    answer2 = mymath.modulus(a,b)
    print(f'{a} ^ {b} = {answer1}')
    print(f'{a} % {b} = {answer2}')



~                                                                                                   
~                                         
import random
ans=5
guess=0
while True:
    guess = random.randint(3,7)
    print(f"Computer guesses: {guess}")
    if guess != ans:
            continue #next iteration of loop
    print('Winner!')
    break #break out of loop altogether

